sudo: required
dist: trusty
addons:
  chrome: stable
language: node_js
node_js:
  - 10.15.3
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - npm install
script:
  - npm run test -- --watch=false
